[build]
    functions = "functions"
    
[[redirects]]
    from = "/webhook/*"
    to = "/.netlify/functions/webhook"
    status = 200

[[redirects]]
    from = "/*"
    to = "/.netlify/functions/:splat"
    status = 200